url: https://evanm.website
permalink: /:year/:month/:title/
highlighter: rouge
markdown: kramdown
future: true
sass:
  dir: css
  style: compressed
plugins:
  - jekyll-gist
  - jekyll-minifier
  - jekyll-sitemap
